### ISSUE TITLE
throws an exception in ObjectMaterialized on untracked entities

### ISSUE THREAD

**Issue by elovelan** [dombrovsky/EntityHooks#7]
[`ObjectStateManager.GetObjectStateEntry`](/dombrovsky/EntityHooks/blob/master/src/System.Data.Entity.Hooks/DbContextHooker.cs#L84) will throw an exception of `The ObjectStateManager does not contain an ObjectStateEntry with a reference to an object of type T` when an entity has been marked with `AsNoTracking()`

**Comment by elovelan** [comment]
I'll take a stab at a fix but just wanted to post this first for discussion

**Comment by dombrovsky** [comment]
That is something need to be fixed.
My guess is that even if you don't want to track changes on loaded entities, you still might want to execute load hooks. ObjectMaterialized should use more forgiving TryGetObjectStateEntry though. Does that make sense?

**Comment by elovelan** [comment]
Yes! I wasn't sure what method to use but that seems reasonable

**Comment by sebastianslutzky** [comment]
hi, has this been fixed? I'm hitting the same error
